Repository code-sum/Best11, pull requests merged in 2022-11, with the labels that each got.

#1 선수단 모델 생성 및 create views 생성
  korea/forms.py
  korea/migrations/0001_initial.py
  korea/models.py
  korea/templates/korea/create_player.html
  korea/urls.py
  korea/views.py
Labels: feature, BE

#2 feat : players에 대한 comment url 및 모델 작성
  korea/models.py
  korea/urls.py
  korea/views.py
Labels: feature, BE

#4 선수 create 구현, 모델 이미지 저장 경로 수정
  korea/templates/korea/create_player.html
  korea/templates/korea/detail_player.html
  korea/templates/korea/index.html
  korea/urls.py
  korea/views.py
Labels: feature, BE

#5 feat: acoounts 모델 생성 및, 로그인, 로그아웃, 내정보, 탈퇴
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_profile_image.py
  accounts/models.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/index.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  config/settings.py
Labels: feature, BE

#6 선수 디테일 구현
  korea/migrations/0002_comment.py
  korea/models.py
  korea/templates/korea/detail_player.html
  korea/views.py
Labels: feature, BE

#7 feat: 회원정보 수정, 비밀번호변경, 팔로우 추가
  accounts/forms.py
  accounts/templates/accounts/change_password.html
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/update.html
  accounts/urls.py
  accounts/views.py
Labels: feature, BE

#9 chore/accounts: 회원정보 수정시 프로필 이미지 변경 가능
  accounts/forms.py
  accounts/templates/accounts/update.html
  accounts/views.py
Labels: BE, update

#10 선수 삭제 구현
  images/chicken-strips.jpg
  korea/templates/korea/create_player.html
  korea/templates/korea/detail_player.html
  korea/templates/korea/index.html
  korea/templates/korea/update_player.html
  korea/urls.py
  korea/views.py
Labels: feature, BE

#11 feat : 뇌피셜 작성 summernote editor 적용
  config/settings.py
  config/urls.py
  korea/forms.py
  korea/migrations/0002_comment.py
  korea/templates/korea/comment_create.html
  korea/urls.py
  korea/views.py
  requirements.txt
Labels: feature, BE

#12 players fans(선수 찜하기) 모델 테이블 추가
  accounts/migrations/0001_initial.py
  images/106902415_bKgVC0I.jfif
  images/5edca96d6d11e6194314.jpg
  korea/migrations/0001_initial.py
  korea/migrations/0002_comment.py
  korea/migrations/0002_players_fans.py
  korea/models.py
  requirements.txt
Labels: BE, update

#13 chore: accounts/exp 코드 수정(감독시 확인 필요)
  accounts/templates/accounts/detail.html
  accounts/views.py
  korea/migrations/0001_initial.py
Labels: BE, update

#14 관리자만 선수 CRUD 가능 & 찜하기 기능 구현
  korea/templates/korea/detail_player.html
  korea/urls.py
  korea/views.py
Labels: feature, BE

#16 feat/korea/comment: 뇌피셜 작성시 exp +1 추가
  korea/views.py
Labels: feature, BE

#17 feature : Add footer, top btn
  korea/views.py
  requirements.txt
  static/css/style.css
  static/images/간정진.jpg
  static/images/베스트일레븐 로고.png
  static/images/이수경.jpg
  static/images/임선주.jpg
  static/images/주세환.jpg
  static/images/차화영.jpg
  templates/base.html
Labels: feature, FE

#19 Base/header
  accounts/views.py
  static/css/style.css
  static/images/Soccer-Ball.png
  static/images/Soccer-Ball2.png
  static/images/logo.png
  templates/base.html
Labels: feature, FE

#20 feat : 선수 detail 페이지에서 comment 좋아요 기능 구현 및 comment와 좋아요 갯수 추가
  images/django-summernote/2022-11-29/15b2e772-4013-467f-a42c-320ba5a506be.jpg
  images/django-summernote/2022-11-29/174a6a80-3d4d-421d-bb10-d15e7694c4ef.jpg
  images/django-summernote/2022-11-29/59a4e32b-3fb0-408a-8c12-8bdcc27c1141.jpg
  images/django-summernote/2022-11-29/91d3fb47-bbc8-45e5-bfd7-f79241735f44.jpg
  korea/templates/korea/comment_create.html
  korea/templates/korea/detail_player.html
  korea/urls.py
  korea/views.py
Labels: feature, BE

#21 chore: 감독이 되기위한 조건 완료
  accounts/views.py
Labels: BE, update

#22 chore : 뇌피셜 좋아요에 따른 작성자 EXP 증감
  korea/views.py
Labels: BE, chore

#23 응원하기 비동기 구현 중
  korea/templates/korea/detail_player.html
  korea/views.py
Labels: feature, BE

#24 프로필이미지 수정
  korea/models.py
Labels: BE, update

#27 응원하기 카운트, 버튼 수정
  korea/templates/korea/detail_player.html
  korea/views.py
Labels: BE, update

#28 feat/accounts/detail: 내가 작성한 뇌피셜 보여주기
  accounts/templates/accounts/detail.html
Labels: feature, BE

#29 chore : comment 좋아요 비동기 구현 중
  accounts/views.py
  korea/templates/korea/detail_player.html
  korea/views.py
Labels: BE, chore

#30 feat/accounts/detail: 북마크(찜)한 선수 내정보에서 보여주기
  accounts/templates/accounts/detail.html
Labels: feature, BE

#31 댓글 좋아요 비동기 처리 중
  korea/templates/korea/detail_player.html
  korea/views.py
Labels: BE, update

#32 fix : 뇌피셜 좋아요 갯수 오류 해결
  korea/templates/korea/detail_player.html
Labels: BE, fix

#34 feat: 회원 정보 팔로우 모달창, 북마크 이미지로
  accounts/templates/accounts/detail.html
Labels: feature, BE

#33 chore : remerge
  korea/templates/korea/detail_player.html
Labels: BE, chore

#35 fix: cors, javascript url 변경
  config/settings.py
  korea/templates/korea/detail_player.html
  korea/views.py
  requirements.txt
Labels: fix

#37 비동기 처리 수정
  korea/templates/korea/detail_player.html
  korea/views.py
Labels: BE, update
