Repository code-sum/Best11, pull requests merged in 2022-12, with the labels that each got.

#38 팔로우 비동기 처리 중
  accounts/templates/accounts/detail.html
  accounts/views.py
  images/django-summernote/2022-11-30/76707a0d-7a63-4b45-9b88-29fcf906d6c4.jfif
Labels: BE, update

#39 메인 인덱스 코리아인덱스 연결
  config/urls.py
  config/views.py
Labels: BE, update

#40 feat/accounts/detail: 활동지수에 따른 직업 비동기
  accounts/templates/accounts/detail.html
  accounts/views.py
  korea/migrations/0002_players_fans.py
Labels: feature, BE

#41 style : accounts 회원가입, 로그인, 정보수정 레이아웃 정렬 및 디자인 수정
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/templates/accounts/update.html
  korea/views.py
Labels: FE, style

#42 style : accounts 프로필 페이지 디자인
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/detail.html
  config/settings.py
  images/106902415_R01Uqi0.jfif
  images/19fb56bd0d8fe6842965135b2ff33e95_0rYr42i.jpg
  images/5edca96d6d11e6194314_eERZqnx.jpg
  images/decoration_14_images_3.jpg
  images/django-summernote/2022-12-01/3837eff3-4d2f-43e4-b45f-45ad25a4efcf.jpg
  images/django-summernote/2022-12-01/43582ec2-0c86-473b-a17d-5b9af0043232.jpg
  images/django-summernote/2022-12-01/5bb28d5f-0ec7-4c83-b7cd-bb2b64f6b6ed.jpg
  images/django-summernote/2022-12-01/606d2ed5-bec2-4b43-85af-731cf37273f9.png
  images/django-summernote/2022-12-01/6c7e2ecc-69fa-4e0a-93c3-b4b927ba0fe8.jpg
  images/django-summernote/2022-12-01/8c63b120-237e-4ce0-978e-94f96c1b7cc4.jpg
  images/django-summernote/2022-12-01/99e6f7b0-1f90-464d-91fe-071a6f2429e9.jpg
  images/django-summernote/2022-12-01/b1cf1f74-5c75-4292-babf-cf9b34662f68.jpg
  images/django-summernote/2022-12-01/b7f12930-a274-4420-b7bb-cc7c34e76331.jpg
  images/django-summernote/2022-12-01/c69a87d5-c8a6-4c1c-8b15-ba94a5cca903.jpg
  images/django-summernote/2022-12-01/f76a2642-2e6a-4a84-b27e-a9a7803d9d3b.jpg
  images/django-summernote/2022-12-01/ffd04023-f61e-4195-95a8-31f72dbebce0.jpg
  images/다운로드_jtIio3s.jfif
  images/다운로드_tw1k3O9.jfif
  images/쏘니.jpg
  korea/migrations/0001_initial.py
  korea/models.py
  korea/templates/korea/comment_create.html
  korea/templates/korea/detail_player.html
  korea/templates/korea/index.html
  korea/views.py
Labels: FE, style

#44 댓글 좋아요 비동기 처리
  korea/templates/korea/detail_player.html
  korea/templates/korea/index.html
Labels: BE, update

#45 Sugyeong/index1
  accounts/views.py
  korea/templates/korea/index.html
  korea/views.py
  static/css/style.css
  static/images/가나.png
  static/images/우루과이.png
  static/images/태극기.jpg
  static/images/태극기.png
  static/images/포르투갈.png
  templates/base.html
Labels: FE, chore, fix, style

#48 Joo/fix/test
  images/django-summernote/2022-12-02/34013caa-9d6a-47d2-adda-3f69a3583611.jfif
  templates/base.html
Labels: BE, update, fix

#51 인스타그램 url 모델 생성
  config/settings.py
  korea/templates/korea/detail_player.html
  korea/views.py
  sns/__init__.py
  sns/admin.py
  sns/apps.py
  sns/migrations/0001_initial.py
  sns/migrations/__init__.py
  sns/models.py
  sns/tests.py
  sns/views.py
Labels: BE

#53 221205/index
  accounts/forms.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/views.py
  static/css/style.css
Labels: FE, update, style

#58 응원하기, 좋아요 많은 피셜 리스트 업
  korea/templates/korea/index.html
  korea/views.py
Labels: feature, BE

#59 fix : 선수 디테일 페이지에서 모든 선수의 comments가 보이는 이슈 해결
  korea/views.py
Labels: BE, fix

#60 style
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  static/css/style.css
  static/images/주세환.jpg
  templates/SJ/detail_player 원본.html
  templates/base.html
Labels: FE, style

#64 feature : Add game_schedule.html
  templates/SJ/game_schedule.html
Labels: FE

#66 feat: 경기규칙 추가 (base.html에서 주소 넣어줘야함)
  korea/templates/korea/rule.html
  korea/urls.py
  korea/views.py
Labels: feature, BE

#67 feat: 댓글 작성 시 욕설 필터링
  filter.txt
  korea/views.py
Labels: feature, BE

#69 Sj
  korea/models.py
  korea/templates/korea/detail_player.html
  static/css/style.css
Labels: feature, FE, style

#70 221206/index
  korea/templates/korea/index.html
  korea/views.py
  static/css/style.css
  static/images/브라질.png
Labels: FE, update, style

#72 style : korea/index 베스트일레븐 영역 작업완료
  korea/templates/korea/index.html
  static/css/style.css
Labels: FE, update, style

#73 Sj
  korea/templates/korea/detail_player.html
  static/css/style.css
  static/images/IG_logo.png
  static/images/선수프로필/손흥민.png
Labels: feature, FE, style

#75 신고하기 기능 구현 완료
  korea/forms.py
  korea/migrations/0002_block.py
  korea/migrations/0003_auto_20221206_1638.py
  korea/migrations/0004_auto_20221206_1659.py
  korea/migrations/0005_auto_20221206_1700.py
  korea/models.py
  korea/templates/korea/detail_player.html
  korea/urls.py
  korea/views.py
  static/css/style.css
Labels: feature, BE

#80 feature : Add login Modal
  images/django-summernote/2022-12-07/04e033c5-bd03-404c-9f91-96f8366d5b4b.jpg
  korea/templates/korea/detail_player.html
Labels: feature, FE, style

#82 style : accounts/index.html 템플릿 정리
  accounts/templates/accounts/index.html
Labels: FE, update, style

#83 fix : 선수 디테일페지 코드 정렬
  korea/templates/korea/detail_player.html
Labels: FE, fix

#84 feat : 미니게임 구현
  korea/templates/korea/game.html
  korea/templates/korea/game_1p.html
  korea/templates/korea/game_2p.html
  korea/urls.py
  korea/views.py
  static/css/style.css
  static/images/1p.png
  static/images/2p.png
  templates/base.html
Labels: feature, FE

#85 Joo fix
  accounts/templates/accounts/detail.html
  korea/templates/korea/detail_player.html
Labels: BE, fix

#86 fix : accounts/views.py 코드리뷰 및 함수 수정
  accounts/views.py
Labels: BE, update, chore, fix

#87 Feature : Fix top button
  static/css/style.css
  templates/base.html
Labels: feature, FE, style

#88 feature:신고한 피셜 모아보기,신고 취소 기능 추가
  accounts/templates/accounts/report.html
  accounts/urls.py
  accounts/views.py
  korea/urls.py
Labels: feature, BE

#89 feat: 피셜피드에 최신뉴스 보여주기
  accounts/templates/accounts/special_feed.html
  accounts/views.py
  requirements.txt
Labels: feature, BE

#91 221208/accounts
  accounts/templates/accounts/detail.html
  images/django-summernote/2022-12-08/1c0df895-03d5-4240-9c86-5ab0621dcc9c.jpg
  images/django-summernote/2022-12-08/ac748fcd-773b-4919-ab0d-9bb532d1e399.jpg
  korea/templates/korea/index.html
  korea/views.py
  static/css/style.css
  static/images/Soccer-Ball.png
  static/images/프로필배경.jpg
  static/images/프로필배경2.png
Labels: BE, FE, update, chore, fix, style

#92 221208/chores
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/special_feed.html
  accounts/views.py
  korea/templates/korea/index.html
  korea/views.py
  static/css/style.css
  templates/base.html
Labels: BE, FE, update, chore, style

#93 feature : Add 피셜 reload button
  images/django-summernote/2022-12-08/611f0941-5d2a-4d99-b274-ff9f4dc88bd6.jfif
  korea/templates/korea/detail_player.html
  static/css/style.css
  templates/base.html
Labels: feature, FE, style

#94 신고한 피셜 보기 연결
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/report.html
Labels: feature, BE

#95 feature: 신고된 피셜 카운트 표시
  accounts/views.py
  korea/templates/korea/detail_player.html
  korea/views.py
Labels: feature, BE

#96 feat : 경기 일정 페이지 구현
  korea/templates/korea/match.html
  korea/urls.py
  korea/views.py
  static/css/style.css
  templates/base.html
Labels: feature, FE

#97 fix : urls.py - syntaxerror
  korea/urls.py
Labels: BE, chore, fix

#98 update:응원하기 아이콘, 피셜 좋아요 아이콘 교체
  korea/templates/korea/detail_player.html
  korea/views.py
  static/css/style.css
Labels: BE, update

#99 221209/fficialfeed
  accounts/templates/accounts/special_feed.html
  accounts/views.py
  images/django-summernote/2022-12-09/6ddb4bf0-05e7-441c-81cf-7b1118af44cb.jpg
  static/css/style.css
Labels: BE, FE, update, fix, style

#100 update: 축구 규칙 디자인 변경
  korea/templates/korea/rule.html
  static/css/style.css
Labels: FE, update

#101 chore: 주석 및 필요없는 코드 삭제 정리
  korea/templates/korea/rule.html
Labels: chore

#102 221210/feed
  accounts/templates/accounts/special_feed.html
Labels: FE, update, chore, style

#103 chore : 2인게임 scroll 막기 & 페이지 title 다듬기
  korea/templates/korea/game.html
  korea/templates/korea/game_1p.html
  korea/templates/korea/game_2p.html
  korea/templates/korea/match.html
Labels: FE, chore

#104 221211/feed
  accounts/templates/accounts/special_feed.html
  static/css/style.css
Labels: FE, update, style

#105 chore : 경기 일정 update
  korea/templates/korea/match.html
Labels: chore

#106 style : 축구규칙 디자인 수정
  korea/templates/korea/rule.html
  static/css/style.css
  templates/base.html
Labels: FE, style

#107 chore : 경기일정 페이지 네브바 수정
  korea/templates/korea/match.html
Labels: FE, chore

#108 Joo 12 1
  accounts/templates/accounts/report.html
  config/settings.py
  korea/template_tags/__init__.py
  korea/template_tags/custom_tags.py
  korea/templates/korea/detail_player.html
  korea/views.py
Labels: feature, BE, update

#109 upgrade:베스트11 선수 응원하기 아이콘 수정
  korea/templates/korea/index.html
Labels: BE, update

#110 feat: 피셜 좋아요순, 최신순 정렬
  korea/templates/korea/detail_player.html
  korea/views.py
  static/css/style.css
Labels: feature, BE, FE

#111 221212/feed
  accounts/templates/accounts/special_feed.html
  static/css/style.css
Labels: FE, update, chore, style

#112 Sj
  config/views.py
  korea/templates/korea/detail_player.html
  static/css/style.css
  templates/base.html
  templates/main.html
Labels: feature, FE, fix

#113 fix : 선수 디테일 페이지
  korea/templates/korea/detail_player.html
Labels: FE, fix

#114 fix: 마이페이지, 피셜 정렬 욕설 필터(수정필요)
  accounts/templates/accounts/detail.html
  accounts/views.py
  korea/views.py
Labels: BE, fix

#115 style : 미니게임&축구규칙&경기일정 header 디자인 수정
  korea/templates/korea/game.html
  korea/templates/korea/match.html
  korea/templates/korea/rule.html
Labels: FE, style

#116 221213/feed
  accounts/templates/accounts/special_feed.html
  static/css/style.css
Labels: FE, update, chore, style

#117 fix: 피셜 최신순 정렬시 좋아요,삭제,신고 수정
  korea/templates/korea/detail_player.html
Labels: BE, fix

#118 Sj
  config/views.py
  static/css/style.css
  static/images/main_iPhone.png
  static/images/main_웹.png
  templates/main.html
Labels: FE, style

#120 221213/feed2
  accounts/templates/accounts/special_feed.html
  static/css/style.css
Labels: FE, update, style

#121 Joo 13 1
  accounts/templates/accounts/report.html
  korea/templates/korea/rule.html
Labels: BE, update

#123 style : 축구규칙 페이지 accordian으로 변경
  korea/templates/korea/rule.html
Labels: FE, style

#122 update: 피셜피드 욕설 필터링
  accounts/views.py
Labels: BE, update

#124 fix : 축구규칙 remerge
  korea/templates/korea/rule.html
Labels: BE, fix

#126 221213/final
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/special_feed.html
  korea/templates/korea/game.html
  korea/templates/korea/index.html
  korea/templates/korea/match.html
  korea/templates/korea/rule.html
  static/css/style.css
  templates/base.html
Labels: FE, update, chore, fix, style

#127 chore : 경기일정 날짜 수정
  korea/templates/korea/match.html
Labels: chore

#128 fix: 반응형 오류 부분 수정(선수 디테일)'
  korea/templates/korea/detail_player.html
Labels: BE, fix

#129 221214/final
  accounts/templates/accounts/detail.html
  static/css/style.css
  templates/main.html
Labels: FE, update, chore, style

#130 fix: 반응형 피셜 재수정
  korea/templates/korea/detail_player.html
  static/css/style.css
Labels: BE, fix

#131 fix: 신고한 피셜 분기처리
  accounts/templates/accounts/detail.html
Labels: BE, fix

#132 docs : README.md 업데이트
  README.md
Labels: documentation, update

#133 docs : README.md 업데이트(2)
  README.md
  config/settings.py
Labels: documentation, update

#134 chore : SNS 공유용 OG 태그 수정
  static/thum.png
  templates/base.html
  templates/main.html
Labels: FE, update, chore

#135 chore : SNS 공유용 OG 태그 수정
  templates/base.html
  templates/main.html
Labels: chore

#136 chore : SNS 공유용 OG 태그 수정(로고이미지 추가)
  templates/base.html
  templates/main.html
Labels: update, chore

#137 docs : comments 좋아요 순 출력과 관련한 메서드 정리
  notes/차화영/베스트일레븐_1220.md
Labels: documentation

#138 chore : 마크다운 오탈자 수정
  notes/차화영/베스트일레븐_1220.md
Labels: documentation, chore

#139 chore : markdown 오탈자 수정
  notes/차화영/베스트일레븐_1220.md
Labels: documentation, chore

#141 docs : AWS MFA 할당하는 법 정리
  notes/이수경/images/mfa_1.png
  notes/이수경/images/mfa_10.png
  notes/이수경/images/mfa_11.png
  notes/이수경/images/mfa_2.png
  notes/이수경/images/mfa_3.png
  notes/이수경/images/mfa_4.png
  notes/이수경/images/mfa_5.png
  notes/이수경/images/mfa_6.png
  notes/이수경/images/mfa_7.jpg
  notes/이수경/images/mfa_8.png
  notes/이수경/images/mfa_9.png
  notes/이수경/베스트일레븐_1222.assets/mfa_1.png
  notes/이수경/베스트일레븐_1222.assets/mfa_10.png
  notes/이수경/베스트일레븐_1222.assets/mfa_11.png
  notes/이수경/베스트일레븐_1222.assets/mfa_2.png
  notes/이수경/베스트일레븐_1222.assets/mfa_3.png
  notes/이수경/베스트일레븐_1222.assets/mfa_4.png
  notes/이수경/베스트일레븐_1222.assets/mfa_5.png
  notes/이수경/베스트일레븐_1222.assets/mfa_6.png
  notes/이수경/베스트일레븐_1222.assets/mfa_7.jpg
  notes/이수경/베스트일레븐_1222.assets/mfa_8.png
  notes/이수경/베스트일레븐_1222.assets/mfa_9.png
  notes/이수경/베스트일레븐_1222.md
Labels: documentation

#142 chore : AWS MFA 문서 오타수정
  notes/이수경/베스트일레븐_1222.md
Labels: documentation, chore
