Repository code-sum/Best11, pull requests merged in 2023-01, with the labels that each got.

#144 update: note 작성
  notes/주세환/assets/image-20230104101141883.png
  notes/주세환/assets/image-20230104102127133.png
  notes/주세환/assets/image-20230104102347319.png
  notes/주세환/assets/image-20230104102544434.png
  notes/주세환/assets/image-20230104102623765.png
  notes/주세환/assets/image-20230104102953921.png
  notes/주세환/assets/image-20230104104551100.png
  notes/주세환/assets/image-20230104104824292.png
  notes/주세환/assets/image-20230104105548662.png
  notes/주세환/assets/image-20230104105732768.png
  notes/주세환/베스트일에븐_1226.md
Labels: update

#146 0105 코드리뷰
  notes/차화영/베스트일레븐_0105.md
Labels: documentation

#149 docs : [FE] 메인화면 구현 1/4 파트 정리
  notes/이수경/images/FE_main_1.png
  notes/이수경/images/FE_main_2.png
  notes/이수경/images/FE_main_3.png
  notes/이수경/베스트일레븐_0124.assets/FE_main_1.png
  notes/이수경/베스트일레븐_0124.assets/FE_main_2.png
  notes/이수경/베스트일레븐_0124.assets/FE_main_3.png
  notes/이수경/베스트일레븐_0124.md
Labels: documentation, FE

#150 chore : [FE] 메인화면 구현 1/4 파트 오타수정
  notes/이수경/베스트일레븐_0124.md
Labels: documentation, FE
